DELETE FROM CENTROS;
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('H12O','Hospital doce de octubre');
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('CSSF','Centro de salud San Fermin');
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('CESP','Centro de Especialidades');
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('CSMV','Centro de Salud Mental Villaverde');




