INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('CIRGEN','Cirugía General');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('DER','Dermatología');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('PED','Pediatría');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('TRA','Traumatología');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('TRAHOS','Traumatología Hospitalización');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('DIGHOS','Digestivo Hospitalización');
INSERT INTO SERVICIOS (CODIGO, DESCRIPCION) VALUES('CARHOS','Cardiología Hospitalización');
