DELETE ALL FROM CENTROS;
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('H12O','Hospital doce de octubre');
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('CSSF','Centro de salud San Fermin');
INSERT INTO CENTROS(CODIGO, DESCRIPCION) VALUES('CELA','Centro de Especialidades Los Ángeles');